global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pytest-monitoring'
    static_configs:
      - targets: ['pytest-exporter:8000']
    scrape_interval: 5s
    metrics_path: /metrics
